# PART1 簡単な予測モデルを作ってみよう

## おまじない

In [2]:
from google.colab import drive
drive.mount('/content/drive')
!pip install japanize-matplotlib
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import japanize_matplotlib
%matplotlib inline
from google.colab import drive
drive.mount('/content/drive')
from sklearn.linear_model import LinearRegression as LR

Mounted at /content/drive
     |████████████████████████████████| 4.1 MB 12.9 MB/s 
  Created wheel for japanize-matplotlib: filename=japanize_matplotlib-1.1.3-py3-none-any.whl size=4120274 sha256=70896bdea3e1a305f3fc23e0e5733ba874bec567b63958385534c80ab0b28674
  Stored in directory: /root/.cache/pip/wheels/83/97/6b/e9e0cde099cc40f972b8dd23367308f7705ae06cd6d4714658
Successfully built japanize-matplotlib
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## データの読み込み
- train.csvとtest.csvとsample.csvの３つのファイルを読み込みましょう
- それぞれを読み込んだものは変数はtrain, test, sampleに代入しましょう
- sampleを読み込む時は、header=Noneというオプションを忘れないようにしましょう

In [3]:
train = pd.read_csv('/content/drive/MyDrive/practice/practice_data/train.csv')
test = pd.read_csv('/content/drive/MyDrive/practice/practice_data/test.csv')
sample = pd.read_csv('/content/drive/MyDrive/practice/practice_data/sample.csv', header = None)

## trainの先頭行を見てみましょう

In [ ]:
train.head()

datetime    y week  soldout  ... payday  weather precipitation temperature
0  2013-11-18   90    月        0  ...    NaN       快晴            --        19.8
1  2013-11-19  101    火        1  ...    NaN       快晴            --        17.0
2  2013-11-20  118    水        0  ...    NaN       快晴            --        15.5
3  2013-11-21  120    木        1  ...    NaN       快晴            --        15.2
4  2013-11-22  130    金        1  ...    NaN       快晴            --        16.1

[5 rows x 12 columns]

## trainから説明変数と目的変数となるデータを取り出しましょう
- 説明変数はtrainからtemperatureを選択し、変数名をtrainXとして代入しましょう
- 目的変数はtrainからyを選択し、変数名をyとして代入しましょう

In [4]:
trainX = train['temperature']
y = train['y']


## testから説明変数となるデータを取り出しましょう
- 説明変数はtrainと同じtemperatureを選択し、変数名をtestXとして代入しましょう

In [5]:
testX = test['temperature']

## 単回帰の場合のみ、説明変数に対しておまじないが必要となります
- 単回帰の場合はややこしいですが、train,testの説明変数ともに、データの形を整える必要があります
- 具体的にはvalues.reshape(-1,1)というおまじないをします
- 整えた後、再び変数Xに代入します

In [6]:
trainX = trainX.values.reshape(-1, 1)
testX = testX.values.reshape(-1, 1)

## 回帰のモデルの箱を用意しましょう
- モデルを作る為にはまず、モデルを表す箱が必ず必要になります
- 変数名をmodel1として、LR()を代入しましょう

In [7]:
model1 = LR()

## 単回帰モデルを作りましょう
- fit関数を使います
- カッコの中に、説明変数、目的変数の順番に書きます

In [8]:
model1.fit(trainX, y)

LinearRegression()

## 作ったモデルの傾きや切片を確かめてみましょう
- 傾きはcoef_を使います
- 切片はintercept_を使います

In [ ]:
model1.coef_

array([-2.5023821])

In [ ]:
model1.intercept_

134.79948383749922

## 予測をしましょう
- predict関数を使います
- 予測結果は変数predに代入しましょう

In [9]:
pred = model1.predict(testX)

In [10]:
pred

array([ 84.25136537,  74.99255159,  62.9811175 ,  80.99826864,
        79.49683938,  76.49398085,  78.49588653,  69.48731097,
        67.73564349,  95.76232304,  88.25517673,  77.24469548,
        74.99255159,  84.25136537,  96.01256125,  98.01446693,
        88.00493852,  77.99541011,  87.00398568,  85.75279463,
        85.75279463,  87.75470031,  87.5044621 ,  94.7613702 ,
        86.75374747,  84.50160358,  81.74898327,  98.01446693,
        98.76518156,  86.00303284,  95.26184662,  99.01541977,
        94.51113199,  97.51399051, 108.52447176,  97.51399051,
       106.27232787, 111.7775685 ,  97.01351409,  96.51303767])

## sampleの中身を確認してみましょう

In [11]:
sample.head()

0   1
0  2014-10-1  24
1  2014-10-2  71
2  2014-10-3  25
3  2014-10-6  32
4  2014-10-7  60

## sample[1]に予測結果を代入しましょう

In [12]:
sample[1] = pred

In [13]:
sample.head()

0          1
0  2014-10-1  84.251365
1  2014-10-2  74.992552
2  2014-10-3  62.981117
3  2014-10-6  80.998269
4  2014-10-7  79.496839

## sampleをファイルで書きだしましょう
- to_csv関数を使います
- オプションは３つあり、"submit1.csv", index=None, header=Noneを書きます

In [ ]:
sample.to_csv('submit1.csv', index = None, header = None)

# 実習
1.説明変数をkcalとして、単回帰モデルを作ろう。まず、 trainとtestのkcalに欠損値があるかないか確認しよう
- 本当に欠損があるかどうか、head関数を使って確認しよう

In [ ]:
train.head()

datetime    y week  soldout  ... payday  weather precipitation temperature
0  2013-11-18   90    月        0  ...    NaN       快晴            --        19.8
1  2013-11-19  101    火        1  ...    NaN       快晴            --        17.0
2  2013-11-20  118    水        0  ...    NaN       快晴            --        15.5
3  2013-11-21  120    木        1  ...    NaN       快晴            --        15.2
4  2013-11-22  130    金        1  ...    NaN       快晴            --        16.1

[5 rows x 12 columns]

In [ ]:
test.head()

datetime week  soldout  ... weather  precipitation temperature
0  2014-10-1    水        1  ...       雨              0        20.2
1  2014-10-2    木        0  ...       曇             --        23.9
2  2014-10-3    金        0  ...      晴れ             --        28.7
3  2014-10-6    月        1  ...       雨            0.5        21.5
4  2014-10-7    火        0  ...      晴れ             --        22.1

[5 rows x 11 columns]

2.trainのkcalの平均値を求め、変数avgに代入しよう

In [ ]:
avg = train['kcal'].mean()

3.変数avgを使って、trainとtestのkcalの欠損値を補間し、それぞれを変数名trainXとtestXに代入してみよう

In [ ]:
trainX = train['kcal'].fillna(avg)
testX = test['kcal'].fillna(avg)

4.trainXとtestXをvalues.reshape(-1,1)を使って形を整え、再びtrainX, testXへ代入しよう
    1. 3番ではtrainXにはavgで補間されたtrain["kcal"]が代入される
    2. 4番では補間されたtrainXにおまじないをかけたものがtrainXに代入されることになる

In [ ]:
trainX = trainX.values.reshape(-1, 1)
testX = testX.values.reshape(-1, 1)


5.trainからyを取り出し、変数yに代入しよう

In [ ]:
y = train['y']

6.回帰モデルの箱を変数名model2として用意しよう

In [ ]:
model2 = LR()

7.trainXとyを使って単回帰のモデルを作ろう

In [ ]:
model2.fit(trainX, y)

LinearRegression()

8.作ったモデルの傾きと切片を確認しよう

In [ ]:
model2.coef_

array([0.13195178])

In [ ]:
model2.intercept_

33.26061577029441

9.testXを使って予測をし、予測値を変数pred2に代入しよう

In [ ]:
pred2 = model2.predict(testX)

10.sample[1]にpred2を代入しよう

In [ ]:
sample[1] = pred2

11.to_csv関数のindex=Noneがある時とない時の違い、header=Noneがある時とない時の違いは何かを考えてみよう

12.sampleをファイル出力し、submit2.csvという投稿用ファイルを作ろう

In [ ]:
sample.to_csv('submit2.csv',index = None, header = None)

13.submit2.csvをDeepAnalyticsに投稿して、submit1.csvのスコアを比較してみよう